const cryptoList = {
	'BTC': {
		name: 'Bitcoin',
		ticker: 'BTC',
		sign: '₿',
		created: '',
		fork: '',
		consensusType: '',
		selected: false,
	},
	'ETH': {
		name: 'Ethereum',
		ticker: 'ETH',
		sign: '',
		created: '',
		fork: '',
		consensusType: '',
		selected: false,
	},
	'XRP': {
		name: 'XRP',
		ticker: 'XRP',
		sign: '',
		created: '',
		fork: '',
		consensusType: '',
		selected: false,
	},
	'BCH': {
		name: 'Bitcoin Cash',
		ticker: 'BCH',
		sign: '',
		created: '',
		fork: '',
		consensusType: '',
		selected: false,
	},
	'BSV': {
		name: 'Bitoin SV',
		ticker: 'BSV',
		sign: '',
		created: '',
		fork: '',
		consensusType: '',
		selected: false,
	},
	'LTC': {
		name: 'Litecoin',
		ticker: 'LTC',
		sign: '',
		created: '',
		fork: '',
		consensusType: '',
		selected: false,
	},
	'BNB': {
		name: 'Binance Coin',
		ticker: 'BNB',
		sign: '',
		created: '',
		fork: '',
		consensusType: '',
		selected: false,
	},
	'EOS': {
		name: 'EOS',
		ticker: 'EOS',
		sign: '',
		created: '',
		fork: '',
		consensusType: '',
		selected: false,
	},
	'XTZ': {
		name: 'Tezos',
		ticker: 'XTZ',
		sign: '',
		created: '',
		fork: '',
		consensusType: '',
		selected: false,
	},
	'LINK': {
		name: 'Chainlink',
		ticker: 'LINK',
		sign: '',
		created: '',
		fork: '',
		consensusType: '',
		selected: false,
	},
	'XLM': {
		name: 'Stellar',
		ticker: 'XLM',
		sign: '',
		created: '',
		fork: '',
		consensusType: '',
		selected: false,
	},
	'XMR': {
		name: 'Monero',
		ticker: 'XMR',
		sign: '',
		created: '',
		fork: '',
		consensusType: '',
		selected: false,
	},
	'ADA': {
		name: 'Cardano',
		ticker: 'ADA',
		sign: '',
		created: '',
		fork: '',
		consensusType: '',
		selected: false,
	},
	'TRX': {
		name: 'Tron',
		ticker: 'TRX',
		sign: '',
		created: '',
		fork: '',
		consensusType: '',
		selected: false,
	},
	'DASH': {
		name: 'Dash',
		ticker: 'DASH',
		sign: '',
		created: '',
		fork: '',
		consensusType: '',
		selected: false,
	},
	'ETC': {
		name: 'Ethereum Classic',
		ticker: 'ETC',
		sign: '',
		created: '',
		fork: '',
		consensusType: '',
		selected: false,
	},
};

const cryptoAbbrevList = [
	'BTC',
	'ETH',
	'XRP',
];

const fiatList = {
	'USD': {
		name: 'US Dollar',
		ticker: 'USD',
		sign: '$',
		created: '',
		fork: '',
		consensusType: '',
		selected: false,
	},
	'EUR': {
		name: 'Euro',
		ticker: 'EUR',
		sign: '€',
		created: '',
		fork: '',
		consensusType: '',
		selected: false,
	},
	'MXN': {
		name: 'Mexican Peso',
		ticker: 'MXN',
		sign: '$',
		created: '',
		fork: '',
		consensusType: '',
		selected: false,
	},
	'AUD': {
		name: 'Australian dollar',
		ticker: 'AUD',
		sign: '$',
		created: '',
		fork: '',
		consensusType: '',
		selected: false,
	},
	'JPY': {
		name: 'Japanese yen',
		ticker: 'JPY',
		sign: '¥',
		created: '',
		fork: '',
		consensusType: '',
		selected: false,
	},
	'KRW': {
		name: 'Korean won',
		ticker: 'KRW',
		sign: '₩',
		created: '',
		fork: '',
		consensusType: '',
		selected: false,
	},
};

export { cryptoList, cryptoAbbrevList, fiatList };